# Matrix Multiplication

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.random.randn(14,10)
B = np.random.randn(14,10)
C = np.random.randn(10,14)

np.shape(C@B)

(10, 10)

In [8]:
def matrix_mult(A,B):
    
    # get matrix sizes
    size_A = np.shape(A)
    size_B = np.shape(B)
    
    if size_A[1] != size_B[0]:
        raise ValueError('Inner dimensions do not match')
        
    C = np.zeros((size_A[0],size_B[1]))
    
    for i in range(size_A[0]):
        for j in range(size_B[1]):
            C[i,j] = np.dot(A[i,:],B[:,j])
            
    return C

In [12]:
A = np.random.randn(4,6)
B = np.random.randn(6,4)

In [15]:
c1 = matrix_mult(A,B)
c2 = A@B

print(c1)
print(c2-c1,2))

[[-1.33775966  0.58699249  0.17325648  0.85781768]
 [ 0.85217028  2.58602054  0.7077207   2.3721549 ]
 [-0.98541521 -2.41162464 -2.95682821 -2.63480425]
 [ 2.1963014  -4.27974859 -2.99216784 -4.40520583]]


TypeError: type numpy.ndarray doesn't define __round__ method